version: 2
registries:
  rubygems-server-rubygems-pkg-github-com:
    type: rubygems-server
    url: https://rubygems.pkg.github.com
    username: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  insecure-external-code-execution: allow
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Central
  open-pull-requests-limit: 10
