require:
  - rubocop-rspec

AllCops:
  Exclude:
    - "app/controllers/rails/health_controller.rb"
    - "db/migrate/201*.rb"
    - "db/migrate/2020*.rb"
    - "db/versions_migrate/201*.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "**/bin/*"
    - "lib/proto/**/*" # ignore computer generated gRPC files
  NewCops: enable
  SuggestExtensions: false

Gemspec/RequireMFA:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - Gemfile

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Naming/InclusiveLanguage:
  Exclude:
    - "db/migrate/2020*.rb"
    - "app/models/shop_directory_setting.rb"

Naming/VariableNumber:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GlobalVars:
  AllowedVariables:
    [$config, $redis, $sidekiq_shutdown_pending, $kafka, $kafka_async_producer]

Style/GuardClause:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/update

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: true
  Exclude:
    - "**/app/jobs/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Rspec cops
RSpec/AnyInstance:
  Enabled: false # disabled until we determine the right foundation for testing philosophy
RSpec/ContextWording:
  Enabled: false
RSpec/EmptyLineAfterExampleGroup:
  Enabled: false
RSpec/EmptyLineAfterHook:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/HookArgument:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 15
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/NoExpectationExample:
  Enabled: false
RSpec/NotToNot:
  Enabled: false
RSpec/PredicateMatcher:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
